### ISSUE TITLE
Audio Keeps on loop for fix duration(fix duration depend's on song length) of Seconds 

### ISSUE THREAD

**Issue by Avinashoo7** [arielfaur/ionic-audio#132]
When I had installed ionic-audio module for ionic 3, it's work fine for some tracK but after that it's keep on looping for fix duration of second.

**Comment by ANANDAN0693** [comment]
i made some come changes in ionic -audio-track-progress-component.ts
`<ion-range [(ngModel)]="range" min="0" max="100" (ngModelChange)="seekTo()" name="progress" ngDefaultControl> <time *ngIf="showProgress" range-left>{{audioTrack.progress | audioTime}}</time> <time *ngIf="showDuration" range-right>{{audioTrack.duration | audioTime}}</time> </ion-range>`
i just changed (ionChange) to (ngModelChange) now its working fine

**Comment by betatools** [comment]
Fix not working for me on 3.0.4

**Comment by arielfaur** [comment]
This hasn't been fixed yet

**Comment by betatools** [comment]
I changed (ionChange)=\"seekTo()\" to (ngModelChange)=\"seekTo()\" in both ionic-audio-track-progress-component.js and ionic-audio-track-progress-component.metadata.json and so far it works even with the --prod flag. Testes on both Android and iOS

Dunno if that helps in the progress of a fix

**Comment by arielfaur** [comment]
This has been fixed in `3.1.0`. I refactored the progress bar component which was causing trouble. It was based on the Ionic's `ion-range` control that didn't play well with the `seekTo()` functionality. I had to refactor the component using a standard HTML range component which is fully customizable using SASS variables.
