### ISSUE TITLE
Lost connection during playing songs

### ISSUE THREAD

**Issue by roaugusto** [arielfaur/ionic-audio#194]
Hey, maybe I have missed something, but It has a way to return the playing of the song after lost connection?

Do I need to coding something to catch this problem?

Thanks in advance!

**Comment by arielfaur** [comment]
@roaugusto There's no solution for this scenario so far. Depending on the media provider, playback should start when buffering is complete.  If you use web audio provider then you could change the default **preload** strategy to **auto** so that the entire song is loaded before playback starts.

https://www.w3schools.com/tags/att_audio_preload.asp

```
this.myTracks = [{
      src: 'https://archive.org/download/JM2013-10-05.flac16/V0/jm2013-10-05-t12-MP3-V0.mp3',
      artist: 'John Mayer',
      title: 'Why Georgia',
      art: 'img/johnmayer.jpg',
      preload: 'auto' // tell the plugin to preload audio
    },
    ...
```
