### ISSUE TITLE
Play/pause icon delay

### ISSUE THREAD

**Issue by eminos** [arielfaur/ionic-audio#3]
There is a little delay when you press the play button until it switches over to pause, and thereby gives the user any UI feedback. I understand it does this because it first checks the Media, and loads it, and so on, and when the status is right, and it starts playing, it switches to "pause". 

This makes it feel slow and unresponsive. It would be better to just switch it to "pause" as soon as it's pressed, and if an error occurs switch it back to "play" (or even some other "error" icon).

**Comment by arielfaur** [comment]
Yes, I am aware of that and I am trying to find a better approach. Will get back to you soon.
Thanks for the feedback!

**Comment by arielfaur** [comment]
I just released a new version 1.2.2 with that fix. You were right, it seems much more responsive now.
Let me know if it's alright now.

There are again minor breaking changes to the directives, because I also wanted it to be more flexible in terms of templating. The changes are documented, also the sample codepen updated.
Basically:
1. `ion-audio-controls` is used to wrap the play button and loading spinner. You must add both as child elements. That gives you more control over which buttons or spinner to use . Check the demo.
2. `ion-audio-play` is now an attribute directive that can be applied either to any element to trigger playback event.

**Comment by ascendedmasta** [comment]
Works perfect for me.
