### ISSUE TITLE
Plugin should use a background thread warning

### ISSUE THREAD

**Issue by sksshareef** [arielfaur/ionic-audio#30]
Geting this warning in Xcode 
THREAD WARNING: ['Media'] took '11719.759033' ms. Plugin should use a background thread.

**Comment by arielfaur** [comment]
That warning is related to the Cordova Media plugin, which is being used by this module. It is not something that I can control. That plugin is maintained by Cordova.

**Comment by leonardosalles** [comment]
The problem was with js2native bridge. Cordova has different methods to communicate with native library (bridge mode):

- XHR with, w/o or optional payload;
- iframe hash with or w/o payload;
- iframe nav.

In cordova.js you can find iOSExec function. For iOS (except iOS 5) bridge mode is set to IFRAME_NAV.

Previous developer made couple of mistakes when on project design phase - and one of them is that whole content is removed from when view changes. And cordova's too. So cordova gets some error loops and plugins is not working.

The solution is to force XHR bridge mode. I've inserted next code right in my deviceready callback:

cordova.exec.setJsToNativeBridgeMode(cordova.exec.jsToNativeModes.XHR_NO_PAYLOAD);
