### ISSUE TITLE
'onSeek' method ?

### ISSUE THREAD

**Issue by nienlm-hhtv** [arielfaur/ionic-audio#46]
Is it possible to add callback when the user slide the seekbar (e.g onSeekStart, onSeekChange, onSeekEnd,...). I want to retrieve the current track's position. Thks !

**Comment by arielfaur** [comment]
This isn't yet implemented. I never thought that use case would be necessary. It shouldn't be difficult to implement though but I don't have the time right now since I am working on v2 of the plugin to support Ionic 2. Here's a hint so you can do it yourself:
https://github.com/arielfaur/ionic-audio/blob/master/dist/ion-audio.js#L400

Open the `ion-audio.js` file and simply add a new line to broadcast the event after that line above. Then capture that even in your controller. Something along the lines of:
````
        // handle track seek-to
        scope.sliderRelease = function() {
            var pos = scope.track.progress;
            MediaManager.seekTo(pos);
            $rootScope.$broadcast('ionic-audio:seekTo', pos);
        };
 
````

Then somewhere in your controller:
````
$scope.$on('ionic-audio:seekTo', function (e, pos) {
    console.log('Jumping to: ', pos);
})
````

Let me know if it works.

**Comment by nienlm-hhtv** [comment]
it leaves the error
`ReferenceError: $rootScope is not defined`

And I don't know where to insert the rootScope reference

**Comment by nienlm-hhtv** [comment]
it thrown the error `rootScope is not defined`

**Comment by arielfaur** [comment]
You need to inject  $rootScope in your controller

**Comment by nienlm-hhtv** [comment]
just use `scope.$root` instead of $rootScope, and it worked well.
