### ISSUE TITLE
AAC stream support

### ISSUE THREAD

**Issue by stevenroh** [arielfaur/ionic-audio#6]
Hello,
I'm trying to stream an icecast server for a webradio (AAC ext).
In the emulator, it tooks approx 10sec to play sound and in my real device loading never ends.

Do you have any ideas why this thing is occurring ? Does this module is supposed to support live streams ?

Thanks for this great module !

**Comment by arielfaur** [comment]
I don't think this module supports live streaming because it is based on the official Cordova Media plugin, which apparently does not (or at least I haven't found the information anywhere in the documentation).  Here's the plugin the module is based on: https://github.com/apache/cordova-plugin-media/
I found few other options that might work better for you:
- https://github.com/keosuofficial/cordova-audio-stream-plugin
- https://github.com/devgeeks/ExampleHTML5AudioStreaming

These two seem to focus on streaming. Good luck!

**Comment by stevenroh** [comment]
Thanks for your reply @arielfaur !

Will look the links and try.
