### ISSUE TITLE
Issues with multiple tracks

### ISSUE THREAD

**Issue by eminos** [arielfaur/ionic-audio#7]
Great to see this module evolving.
I took an other test run today, and found some issues.
The issues are with multiple tracks. When one track is playing, trying to play an other track doesn't change the first tracks button back to "play icon". Am I missing something?

```javascript
.controller('ExercisesCtrl', function($scope, $ionicPlatform) {
  
  var urlprefix;
  if ($ionicPlatform.is('android')) { urlprefix = '/android_asset/www/' }

  $scope.exercises = [
    { 
      id: 1,
      title: 'Title 1', 
      description: '',
      descriptionlong: '',
      url: urlprefix + 'audio/1.mp3'
    },
    { 
      id: 2,
      title: 'Title 2', 
      description: '',
      descriptionlong: '',
      url: urlprefix + 'audio/2.mp3'
    }
  ];

})
```

```javascript
<div class="list card exercise" ng-repeat="exercise in exercises" toggle-class="active">
  <ion-audio-track track="exercise">
    <div class="item">
        <ion-audio-controls>
          <a class="button button-icon button-stable icon ion-play" ion-audio-play></a>
        </ion-audio-controls>
        <h2>{{exercise.title}}</h2>
        <p>{{exercise.description}}</p>
        <div class="desc-long">
          <p>{{exercise.descriptionlong}}</p>
        </div>
    </div>
  </ion-audio-track>
</div>
```

**Comment by eminos** [comment]
Actually, Pause doesn't work at all for me. (BTW, I'm not using the spinner, I don't need it since it's all local files that start instantly.)

**Comment by arielfaur** [comment]
hmm...interesting. I haven't tested this use case with local files but that shouldn't make a difference. I will run some tests today. Did you by any chance update to the latest version? Because I pushed a new version yesterday and I want to know if it worked fine before with the earlier release. Or did you spot the issue just today by chance?

**Comment by arielfaur** [comment]
I tried different scenarios, including yours, and it all worked fine on my Android devices (4.1.2 and 5.1). Haven't tested on iOS though.
Could you please check out this Ionic project and simply run it on your device(s) ?
https://github.com/arielfaur/ionic-audio-example

Simply add a platform and run it on your device and let me know if you see any issues. I removed the spinner and progress bar just like in your example. I've also added some local mp3 files like you're doing and it all worked fine on my end! Let me know.

**Comment by arielfaur** [comment]
Forgot to add that you must run `bower install` first of all :)

**Comment by ascendedmasta** [comment]
I'll give this a shot on iOS as well.

I've only ever used local files to test with...Seems to have worked fine with me before.

**Comment by arielfaur** [comment]
That'd be great @ascendedmasta ! Thanks!

**Comment by ascendedmasta** [comment]
@eminos  Copying and pasting your code didn't run initially...Not sure what you're trying to do with your exercise/s object array.

I did was @arielfaur did to test as well.

**Comment by arielfaur** [comment]
What if you move `ng-repeat="exercise in exercises"` to the ion-audio-track tag:

`<ion-audio-track ng-repeat="exercise in exercises" track="exercise">`

Does that work for you?

**Comment by ascendedmasta** [comment]
@arielfaur : When I do that I'm able to play both tracks independently and they work. However, the ability to pause either track is disabled so the music plays to the end. 

If exercise track1 is playing when you press exercise track2, track1 stops and track2 starts playing (until it ends) with no ability to stop the track. 

And vice versa.

**Comment by arielfaur** [comment]
This is really weird because the ionic-audio-example project I uploaded to GitHub does exactly that, the code is very similar to @eminos code.
@ascendedmasta did you try with the example project? I am able to play one track, then play the other and still able to pause.
Maybe @eminos can put up a full sample project for us to try ?

**Comment by ascendedmasta** [comment]
Sorry about that...It was a syntax error on my part.

Do both the tracks play at one time?

A quick user test:

If you play another track while that spinner is still active, it will disable the ability to play that other track. I'm guessing that playlist support would correct this issue though.

**Comment by arielfaur** [comment]
Can you upload a project for me to test your use case?

**Comment by nickfogle** [comment]
Has anyone found the root of the pause problems. I'm noticing the same issue on iOS. The only way to stop the current track is to click play for a separate track.

**Comment by arielfaur** [comment]
@nickfogle can you upload a sample project so I can test it? Unfortunately I don't have an iOS device, but I can try with the emulator. On Android everything seems to work fine though.

**Comment by nickfogle** [comment]
@arielfaur After encountering the issue, I tried again using your example project. I installed all dependencies and deployed to my iPhone. I had the exact same issue with the pause button not working. There are no errors in my console, but it's like that pause button doesn't even register the touch. I'm using an iPhone 5s running iOS 8.

**Comment by arielfaur** [comment]
@nickfogle I have been testing the example project on the iOS simulator, tried on the iPhone 5S and works fine at least on the emulator image! I don't have an actual iPhone to test on unfortunately. Although  I have an idea where the problem may come from. I will push some fixes. It would be great if you could give it a try on your iPhone and report back.

**Comment by nickfogle** [comment]
@arielfaur thanks for looking into this. Once you push the updates, I'm happy to test it on my device and let you know how it works.

**Comment by arielfaur** [comment]
@nickfogle I have been looking into the play-pause issue. Since I don't have an iOS device I can only guess where the problem comes from. I would guess it's related to the fact I disabled the play button until the track had fully loaded to avoid the use case of multiple clicks leading to unexpected behavior. Disabling the button element seemed not to work well on iOS apparently. So I have simplified this scenario by preventing multiple clicks.
Could you please test it on your iPhone and let me know? It's still not a release, but a fix to the example project. It's in a new branch so simply check out the project:
https://github.com/arielfaur/ionic-audio-example/tree/fix-play-pause

Note: The project is using a modified `ion-audio.js`, not the one in the master branch:
https://github.com/arielfaur/ionic-audio-example/blob/fix-play-pause/www/js/ion-audio.js

**Comment by nickfogle** [comment]
@arielfaur Nice work! I've tested on iOS and can confirm that the previous issues are now resolved.

**Comment by arielfaur** [comment]
Excellent! I will build a release then. It would be great to get feedback from @eminos and @ascendedmasta too, to be on the safe side :)

**Comment by ascendedmasta** [comment]
Tested on iOS 6, 6 Plus, and iPad Mini. The issues are resolved.

**Comment by arielfaur** [comment]
Thanks a lot for your feedback @ascendedmasta !
