### ISSUE TITLE
Audio player not showing in the emulate ios

### ISSUE THREAD

**Issue by pothagoni** [arielfaur/ionic-audio#72]
**Ionic plugin list**

cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-media 2.3.0 "Media"
cordova-plugin-whitelist 1.2.2 "Whitelist"

**Downloaded the ion-audio script file to lib and added to the index file**

<script type="text/javascript" src="lib/ion-audio/ion-audio.js"></script>

**Code snippet in the controller**
app.controller('liveaudioCtrl', function($scope){
    //console.log('liveaudio controller called ...');
    $scope.myTrack = {
    url: 'audio/less-happy-0x26p.mp3',
    artist: 'Manasutho',
    title: 'Manasutho',
    art: 'img/ve_logo_90x90.png'
}

**directive in the html file**
`<ion-audio-track track="myTrack">`

**Anything I missed adding to my code? Why player is not showing up in ios or andriod?**

**When launch in the browser, I see below error. But this is already mention in the document and know issue.**

ionic-audio: missing Cordova Media plugin. Have you installed the plugin? 
Run 'ionic plugin add cordova-plugin-media'
ionic.bundle.js:26794 TypeError: Cannot read property 'stop' of null
    at ion-audio.js:316
    at Scope.$digest (ionic.bundle.js:30239)
    at Scope.$apply (ionic.bundle.js:30503)
    at HTMLBodyElement.<anonymous> (ionic.bundle.js:26543)
    at defaultHandlerWrapper (ionic.bundle.js:16787)
    at HTMLBodyElement.eventHandler (ionic.bundle.js:16775)
    at triggerMouseEvent (ionic.bundle.js:2953)
    at tapClick (ionic.bundle.js:2942)
    at HTMLDocument.tapMouseUp (ionic.bundle.js:3018)(anonymous function) @ ionic.bundle.js:26794

**Comment by arielfaur** [comment]
Have you tried running the sample project inside the module?

**Comment by tbergeron** [comment]
Inactive issue? Can we close this?

Otherwise:

Hi, I'm not the repository owner but I'm trying to help out as I need to use this package too so I'm doing my best to iron out the remaining issues. I've started to check out the opened issues. There are lots of doubles without any examples whatsoever. I'd like to do some clean up, so first I need to make sure the opened issues are legitimate.

**Please make sure to follow these simple guidelines in the future:**

1) Use the GitHub issue search — check if the issue has already been reported. Check if the issue has been fixed.

2) If none is found, create a new issue by describing your problem, providing example of the boggus code and also make sure to write it with proper syntax and syntax. Re-read your issue twice or more to make sure it will makes sense to the repository owner. He might not even reply if he doesn't understand what's the problem.

A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs.

Example:

> Short and descriptive example bug report title
> 
> A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.
> 
> This is the first step
> This is the second step
> Further steps, etc.
> <url> - a link to the reduced test case
> 
> Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

Once a proper issue description is provided, we will be way more prepared to help you out. Thanks a lot and have a nice day.
