### ISSUE TITLE
Confliction With Corodova File Download

### ISSUE THREAD

**Issue by kapilkarda** [arielfaur/ionic-audio#74]
Hello,

When i trying to download file after that when i tried to play it hangs the device and when i wrap the code into the ionicPlatform then the seekbar is not working, can you please help me in that.

Thanks and Regards,
Kapil Karda

**Comment by tbergeron** [comment]
Inactive issue? Can we close this?

Otherwise:

Hi, I'm not the repository owner but I'm trying to help out as I need to use this package too so I'm doing my best to iron out the remaining issues. I've started to check out the opened issues. There are lots of doubles without any examples whatsoever. I'd like to do some clean up, so first I need to make sure the opened issues are legitimate.

**Please make sure to follow these simple guidelines in the future:**

1) Use the GitHub issue search — check if the issue has already been reported. Check if the issue has been fixed.

2) If none is found, create a new issue by describing your problem, providing example of the boggus code and also make sure to write it with proper syntax and syntax. Re-read your issue twice or more to make sure it will makes sense to the repository owner. He might not even reply if he doesn't understand what's the problem.

A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs.

Example:

> Short and descriptive example bug report title
> 
> A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.
> 
> This is the first step
> This is the second step
> Further steps, etc.
> <url> - a link to the reduced test case
> 
> Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

Once a proper issue description is provided, we will be way more prepared to help you out. Thanks a lot and have a nice day.
