### ISSUE TITLE
http file is not playing

### ISSUE THREAD

**Issue by Shamonshamonsha** [arielfaur/ionic-audio#81]
Only https audio files are played http files not played

**Comment by nicolasguzca** [comment]
Hummm yes they are playing. I serve all my files via http and they play perfectly. Maybe it is an issue with your server?

**Comment by nadimnakade** [comment]
Me also facing the same issue while development where i copied exact code from example over here but it itsn't working. Any help will be very helpful @nicolasguzca in my case audio dont show up only spinner is showing

**Comment by codinronan** [comment]
For anyone else running into this, this will happen on iOS where http requests are by default required to be https on iOS 9 and above. Just enable http-only requests in your plist.

**Comment by nicolasguzca** [comment]
Hello guys, for me it was a CORS issue. 
On the actual device they played perfectly, but on the browser using Ionic Serve only the spinner shows, as @nadimnakade states.

I fixed it using the chrome plugin https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog

**Comment by tbergeron** [comment]
Surely a CORS issue otherwise please review this OP:

Hi, I'm not the repository owner but I'm trying to help out as I need to use this package too so I'm doing my best to iron out the remaining issues. I've started to check out the opened issues. There are lots of doubles without any examples whatsoever. I'd like to do some clean up, so first I need to make sure the opened issues are legitimate.

**Please make sure to follow these simple guidelines in the future:**

1) Use the GitHub issue search — check if the issue has already been reported. Check if the issue has been fixed.

2) If none is found, create a new issue by describing your problem, providing example of the boggus code and also make sure to write it with proper syntax and syntax. Re-read your issue twice or more to make sure it will makes sense to the repository owner. He might not even reply if he doesn't understand what's the problem.

A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs.

Example:

> Short and descriptive example bug report title
> 
> A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.
> 
> This is the first step
> This is the second step
> Further steps, etc.
> <url> - a link to the reduced test case
> 
> Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

Once a proper issue description is provided, we will be way more prepared to help you out. Thanks a lot and have a nice day.
