### ISSUE TITLE
How to make next or back button for playing the playlist?

### ISSUE THREAD

**Issue by jealvin** [arielfaur/ionic-audio#86]
i have test and it's work like a charm
but im confuse about what the tittle just saying :)

**Comment by devshisiyani** [comment]
I am also interested in how you can auto play everything in the playlist.
For now I just was the app to play audio file one after the other indicating which audio file is playing.
Any code snippets would be useful to help me get started

**Comment by arielfaur** [comment]
I haven't implemented the playlist feature yet. I need to update the module to work with the latest Ionic 2 before I can work on any new features.

**Comment by tbergeron** [comment]
There's no previousTrack() nextTrack() so far. I guess you'd need to pause the current track, switch it to the next one and play the track.

```
// next track pseudo code example
let nextTrackIndex = currentTrackIndex+1; // get next track index
this.audioProvider.pause(); // pause current track
this.audioProvider.play(nextTrackIndex); // play next track
```

As for @devshisiyani question please check this https://github.com/arielfaur/ionic-audio/issues/88#issuecomment-304923855

The thing is, this doesn't work fully right now because the player UI doesn't reflect the track change as stated here #106 

I'll update this issue if I do any progress.

**Comment by arielfaur** [comment]
#88
