### ISSUE TITLE
When Stopping audio http requests is not canceled 

### ISSUE THREAD

**Issue by sfaizanh** [arielfaur/ionic-audio#98]
Is there any way to cancel the http request also?

**Comment by arielfaur** [comment]
I don't think so as this is handled by HTML audio or the Media plugin itself

**Comment by tbergeron** [comment]
I agree with @arielfaur on this, the requests are launched automatically because the elements are shown within the page. Only way of preventing them IMO would be to do some kind of lazy loading to prevent these requests until the user scrolls and the items get displayed.

Can we close this issue? This is a question and not really an "issue" with the code.
